# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_weighted_cvb_zero_inference <- function(docs_in, alpha_in, eta_in, K, V, thresh, max_iters, seed, weights_in) {
    .Call(`_LdaFuncs_r_weighted_cvb_zero_inference`, docs_in, alpha_in, eta_in, K, V, thresh, max_iters, seed, weights_in)
}

r_weighted_cvb_zero_predict <- function(docs_in, BETA_in, alpha_in, eta_in, K, V, thresh, max_iters, seed, weights_in) {
    .Call(`_LdaFuncs_r_weighted_cvb_zero_predict`, docs_in, BETA_in, alpha_in, eta_in, K, V, thresh, max_iters, seed, weights_in)
}

